# 应用配置
app:
  name: app
  port: 8088

# 数据库配置
database:
  host: localhost
  port: 3306
  name: devops-platform
  username: root
  password: 123456

# 验证码
captcha:
  key-long: 4
  img-width: 240
  img-height: 40

# 加密
encryption:
  key: 1234567890123456

# jwt
jwt:
  signing-key: fasdfas
  expires-time: 7d
  buffer-time: 1d
  issuer: fasdfas

# redis
redis:
  db: 0
  addr: 192.168.100.24:6379
  password: ""

# minio
minio:
  endpoint : play.min.io
  accessKeyID : Q3AM3UQ867SPQQA43P2F
  secretAccessKey : zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  useSSL : true